/**
 * Object containing all the action types
 */
const types = {
  FETCH_LOCATION_REQUESTED: 'FETCH_LOCATION_REQUESTED',
  FETCH_LOCATION_SUCCEEDED: 'FETCH_LOCATION_SUCCEEDED',
  FETCH_LOCATION_FAILED:    'FETCH_LOCATION_FAILED',
  FETCH_WEATHER_FAILED:     'FETCH_WEATHER_FAILED',
  FETCH_WEATHER_REQUESTED:  'FETCH_WEATHER_REQUESTED',
  FETCH_WEATHER_SUCCEEDED:  'FETCH_WEATHER_SUCCEEDED',
  REQUEST_FAILED:           'REQUEST_FAILED',
  DISMISS_NOTIFICATION:     'DISMISS_NOTIFICATION',
  RESPONSE_FROM_CACHE:      'RESPONSE_FROM_CACHE',
}

export default types