const types = {
  FETCH_LOCATION_REQUESTED: 'FETCH_LOCATION_REQUESTED',
  FETCH_LOCATION_SUCCEEDED: 'FETCH_LOCATION_SUCCEEDED',
  FETCH_WEATHER_REQUESTED:  'FETCH_WEATHER_REQUESTED',
  FETCH_WEATHER_SUCCEEDED:  'FETCH_WEATHER_SUCCEEDED',
}

export default types